<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="catalogo">

        <xs:complexType>

            <xs:sequence>

                <xs:element name="producto" maxOccurs="unbounded">

                    <xs:complexType>

                        <xs:sequence>

                            <xs:element name="id" type="xs:string"/>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="categoria" type="xs:string"/>
                            <xs:element name="descripcion" type="xs:string"/>
                            <xs:element name="precio" type="xs:decimal"/>
                            <xs:element name="marca" type="xs:string"/>
                            <xs:element name="imagen" type="xs:string"/>
                            <xs:element name="disponible" type="xs:string"/>

                        </xs:sequence>

                    </xs:complexType>

                </xs:element>

            </xs:sequence>

        </xs:complexType>

    </xs:element>

</xs:schema>